#ifndef ABSTRACT_SYNTAX_TREE_HEADER
#define ABSTRACT_SYNTAX_TREE_HEADER

#include "../../support/logging/Logger.h"
#include "../../support/type/ModuleDestructor.h"
#include <stdlib.h>

/** Initialize module's internal state. */
ModuleDestructor initializeAbstractSyntaxTreeModule();

/**
 * This type definitions allows self-referencing types (e.g., a topic that is
 * made of another topics).
 */

typedef enum ConstantType ConstantType;
typedef enum DeclarationType DeclarationType;
typedef enum ExpressionType ExpressionType;
typedef enum FactorType FactorType;
typedef enum MemberType MemberType;
typedef enum PeriodType PeriodType;
typedef enum RuleType RuleType;
typedef enum StatementType StatementType;

typedef struct Attribute Attribute;
typedef struct AttributeList AttributeList;
typedef struct Availability Availability;
typedef struct Constant Constant;
typedef struct ConstraintList ConstraintList;
typedef struct Declaration Declaration;
typedef struct DeclarationList DeclarationList;
typedef struct Expression Expression;
typedef struct ExpressionList ExpressionList;
typedef struct Factor Factor;
typedef struct Goal Goal;
typedef struct LevelList LevelList;
typedef struct Member Member;
typedef struct MemberList MemberList;
typedef struct Method Method;
typedef struct Parameter Parameter;
typedef struct ParameterList ParameterList;
typedef struct Period Period;
typedef struct PeriodList PeriodList;
typedef struct Program Program;
typedef struct Rule Rule;
typedef struct RuleList RuleList;
typedef struct Scale Scale;
typedef struct Slot Slot;
typedef struct SlotList SlotList;
typedef struct StatementList StatementList;
typedef struct Statement Statement;
typedef struct Topic Topic;

/**
 * Node types for the Abstract Syntax Tree (AST).
 *
 * The names of this enumerations must never collide with the token labels
 * generated by Bison (e.g., the token is ADD, so the node type is
 * ARITHMETIC_ADD).
 */

enum DeclarationType {
	AVAILABILITY_DECLARATION,
	CONSTRAINTS_DECLARATION,
	GOAL_DECLARATION,
	METHOD_DECLARATION,
	PLAN_DECLARATION,
	RULES_DECLARATION,
	SCALE_DECLARATION,
	TOPIC_DECLARATION
};

enum StatementType {
	AFTER_STATEMENT,
	FOR_STATEMENT,
	PAUSE_STATEMENT,
	REPEAT_STATEMENT,
	SESSION_STATEMENT
};

enum MemberType {
	ATTRIBUTE_MEMBER,
	TOPIC_MEMBER
};

enum PeriodType {
	RANGE_PERIOD,
	SINGLE_PERIOD
};

enum RuleType {
	OTHERWISE_RULE,
	WHEN_RULE
};

enum ExpressionType {
	ARITHMETIC_ADD,
	ARITHMETIC_DIV,
	ARITHMETIC_MUL,
	ARITHMETIC_SUB,
	COMPARE_EQUAL,
	COMPARE_GREATER,
	COMPARE_GREATER_EQUAL,
	COMPARE_LESS,
	COMPARE_LESS_EQUAL,
	COMPARE_NOT_EQUAL,
	FACTOR_EXPRESSION,
	LOGICAL_AND,
	LOGICAL_NOT,
	LOGICAL_OR
};

enum FactorType {
	CONSTANT_FACTOR,
	INVOCATION_FACTOR,
	LIST_FACTOR,
	PARENTHESIZED_FACTOR,
	VARIABLE_FACTOR
};

enum ConstantType {
	DATE_CONSTANT,
	DURATION_CONSTANT,
	INTEGER_CONSTANT,
	STRING_CONSTANT,
	TIME_CONSTANT
};

/**
 * Expressions.
 */

struct Constant {
	union {
		/** The amount of days since the Christian era, encoded as an integer
		 * with the shape yyyymmdd. */
		int date;
		/** The total amount of minutes. */
		int duration;
		int integer;
		/** The amount of minutes since midnight. */
		int time;
		char * string;
	};
	ConstantType type;
};

struct Factor {
	union {
		Constant * constant;
		/** A parenthesized expression. */
		Expression * expression;
		/** The elements of a list literal, or NULL when it's empty. */
		ExpressionList * elements;
		/** The name of a variable. */
		char * variable;
		/** The invocation of a function, where the arguments are NULL when the
		 * invocation has none. */
		struct {
			char * function;
			ExpressionList * arguments;
		};
	};
	FactorType type;
};

struct Expression {
	union {
		Factor * factor;
		/** The operand of an unary operator. */
		Expression * operand;
		struct {
			Expression * leftExpression;
			Expression * rightExpression;
		};
	};
	ExpressionType type;
};

struct ExpressionList {
	Expression * expression;
	ExpressionList * next;
};

/**
 * Scales.
 */

struct LevelList {
	char * level;
	LevelList * next;
};

struct Scale {
	char * name;
	LevelList * levels;
};

/**
 * Methods.
 */

struct Parameter {
	char * name;
	char * type;
};

struct ParameterList {
	Parameter * parameter;
	ParameterList * next;
};

struct Statement {
	union {
		/** The duration of a session or a pause. */
		Expression * duration;
		/** A statement that is delayed in time. */
		struct {
			Expression * delay;
			Statement * delayedStatement;
		};
		/** A block that is executed a fixed amount of times. */
		struct {
			Expression * count;
			StatementList * repeatBody;
		};
		/** A block that is executed once per element of an iterable. */
		struct {
			char * variable;
			Expression * iterable;
			StatementList * forBody;
		};
	};
	StatementType type;
};

struct StatementList {
	Statement * statement;
	StatementList * next;
};

struct Method {
	char * name;
	/** NULL when the method declares no parameters. */
	ParameterList * parameters;
	StatementList * body;
};

/**
 * Goals and topics.
 */

struct Attribute {
	char * name;
	ExpressionList * values;
};

struct Member {
	union {
		Attribute * attribute;
		Topic * topic;
	};
	MemberType type;
};

struct MemberList {
	Member * member;
	MemberList * next;
};

struct Goal {
	char * name;
	/** NULL when the block is empty. */
	MemberList * members;
};

struct Topic {
	char * name;
	/** The goal this topic belongs to, or NULL when it's a nested topic. */
	char * goal;
	/** NULL when the block is empty. */
	MemberList * members;
};

/**
 * Availability.
 */

struct Period {
	union {
		/** A bare duration. */
		Expression * amount;
		/** A time window. */
		struct {
			Expression * from;
			Expression * to;
		};
	};
	PeriodType type;
};

struct PeriodList {
	Period * period;
	PeriodList * next;
};

struct Slot {
	/** The name of a day, or of a set of days. */
	char * day;
	PeriodList * periods;
};

struct SlotList {
	Slot * slot;
	SlotList * next;
};

struct Availability {
	SlotList * slots;
};

/**
 * Constraints.
 */

struct ConstraintList {
	Expression * constraint;
	ConstraintList * next;
};

/**
 * Rules.
 */

struct Rule {
	/** NULL for an OTHERWISE rule. */
	Expression * condition;
	Expression * action;
	RuleType type;
};

struct RuleList {
	Rule * rule;
	RuleList * next;
};

/**
 * Plan.
 */

struct AttributeList {
	Attribute * attribute;
	AttributeList * next;
};

/**
 * Program.
 */

struct Declaration {
	union {
		Availability * availability;
		ConstraintList * constraints;
		Goal * goal;
		Method * method;
		/** The attributes of the plan, or NULL when the block is empty. */
		AttributeList * plan;
		RuleList * rules;
		Scale * scale;
		Topic * topic;
	};
	DeclarationType type;
};

struct DeclarationList {
	Declaration * declaration;
	DeclarationList * next;
};

struct Program {
	DeclarationList * declarations;
};

/**
 * Node recursive destructors.
 */

void destroyAttribute(Attribute * attribute);
void destroyAttributeList(AttributeList * attributeList);
void destroyAvailability(Availability * availability);
void destroyConstant(Constant * constant);
void destroyConstraintList(ConstraintList * constraintList);
void destroyDeclaration(Declaration * declaration);
void destroyDeclarationList(DeclarationList * declarationList);
void destroyExpression(Expression * expression);
void destroyExpressionList(ExpressionList * expressionList);
void destroyFactor(Factor * factor);
void destroyGoal(Goal * goal);
void destroyLevelList(LevelList * levelList);
void destroyMember(Member * member);
void destroyMemberList(MemberList * memberList);
void destroyMethod(Method * method);
void destroyParameter(Parameter * parameter);
void destroyParameterList(ParameterList * parameterList);
void destroyPeriod(Period * period);
void destroyPeriodList(PeriodList * periodList);
void destroyProgram(Program * program);
void destroyRule(Rule * rule);
void destroyRuleList(RuleList * ruleList);
void destroyScale(Scale * scale);
void destroySlot(Slot * slot);
void destroySlotList(SlotList * slotList);
void destroyStatement(Statement * statement);
void destroyStatementList(StatementList * statementList);
void destroyTopic(Topic * topic);

#endif